"""Read a Learning Plan .docx (one produced by this app) back into data.

This is the inverse of `doc_builder`: it walks the single combined table and
reconstructs the `Unit`, the list of `Session`s, and the `PlanInputs` header so a
user can upload an existing Learning Plan and go straight to generating Session
Plans - without re-uploading the Occupational Standard and Curriculum.

The table layout (see doc_builder) is:
  * 5 two-cell heading rows  -> 'Label: value' pairs (Unit of Competence, Unit
    Code, Institution, Name of Trainer, Course, Level, Date of Preparation,
    Number of Trainees, Class),
  * a full-width 'Skill or Job Task:' row,
  * a full-width 'Benchmark or Criteria to be used:' row (elements + PCs),
  * the 9-column session grid: a header row then one row per session.
"""

from __future__ import annotations

import re
from typing import List, Tuple

from docx import Document

from models import Element, PerformanceCriterion, PlanInputs, Session, Unit


class LearningPlanParseError(ValueError):
    """Raised when a .docx does not look like a Learning Plan from this app."""


# --------------------------------------------------------------------------- #
# Cell helpers
# --------------------------------------------------------------------------- #
def _distinct_cells(row) -> list:
    """Return one cell per underlying <w:tc> (merged cells appear once)."""
    out, seen = [], []
    for c in row.cells:
        tc = c._tc
        if tc not in seen:
            seen.append(tc)
            out.append(c)
    return out


def _cell_lines(cell) -> List[str]:
    """Non-empty paragraph texts of a cell, one list item per line."""
    return [p.text.strip() for p in cell.paragraphs if p.text.strip()]


def _split_label_value(text: str) -> Tuple[str, str]:
    label, _, value = text.partition(":")
    return label.strip(), value.strip()


# --------------------------------------------------------------------------- #
# Benchmark (elements + performance criteria) reconstruction
# --------------------------------------------------------------------------- #
_PC_RE = re.compile(r"^(\d+\.\d+)\s+(.*)$")
_EL_RE = re.compile(r"^(\d+)\.\s+(\D.*)$")


def _parse_benchmark(lines: List[str]) -> List[Element]:
    elements: List[Element] = []
    current: Element | None = None
    for ln in lines:
        pc = _PC_RE.match(ln)
        if pc:
            if current is None:
                current = Element(number="1", title="")
                elements.append(current)
            current.performance_criteria.append(
                PerformanceCriterion(number=pc.group(1), text=pc.group(2).strip()))
            continue
        el = _EL_RE.match(ln)
        if el:
            current = Element(number=el.group(1), title=el.group(2).strip())
            elements.append(current)
    return elements


# --------------------------------------------------------------------------- #
# Public API
# --------------------------------------------------------------------------- #
def parse_learning_plan(path: str) -> Tuple[Unit, List[Session], PlanInputs]:
    """Parse a Learning Plan .docx -> (Unit, sessions, PlanInputs).

    Raises LearningPlanParseError when the file has no recognisable session grid.
    """
    doc = Document(path)
    if not doc.tables:
        raise LearningPlanParseError(
            "No table found - this does not look like a Learning Plan produced "
            "by this app.")

    table = doc.tables[0]
    heading: dict = {}
    skill_lines: List[str] = []
    benchmark_lines: List[str] = []
    session_rows: list = []

    for row in table.rows:
        cells = _distinct_cells(row)
        n = len(cells)
        if n == 2:                                    # 'Label: value' pair row
            for c in cells:
                label, value = _split_label_value(c.text)
                if label:
                    heading[label.lower()] = value
        elif n == 1:                                  # full-width Skill / Benchmark
            lines = _cell_lines(cells[0])
            if not lines:
                continue
            head = lines[0].lower()
            if head.startswith("skill or job"):
                skill_lines = lines[1:]
            elif head.startswith("benchmark"):
                benchmark_lines = lines[1:]
        elif n == 9:                                  # session header or data row
            if cells[0].text.strip().lower() == "week":
                continue                              # column-header row -> skip
            session_rows.append(cells)

    if not session_rows:
        raise LearningPlanParseError(
            "No sessions found in the Learning Plan table. Upload a Learning Plan "
            "generated by this app.")

    sessions: List[Session] = []
    for cells in session_rows:
        title = cells[2].text.strip().replace("\n", " ")
        key_points = _cell_lines(cells[4])
        is_cat = (any(k.strip().upper() == "ASSESSMENT COVERAGE" for k in key_points)
                  or bool(re.search(r"\bCAT\b", title, re.I)))
        sessions.append(Session(
            week=int(re.sub(r"\D", "", cells[0].text) or 0),
            session_no=cells[1].text.strip() or "1",
            is_cat=is_cat,
            session_title=title,
            pcs=[],                                   # per-session PCs aren't stored in the plan
            key_points=key_points,
            learning_outcomes=_cell_lines(cells[3]),
            trainee_activities=_cell_lines(cells[5]),
            resources=_cell_lines(cells[6]),
            assessments=_cell_lines(cells[7]),
        ))

    unit = Unit(
        unit_title=heading.get("unit of competence", ""),
        os_code=heading.get("unit code", ""),
        level=heading.get("level", ""),
        skill_task=" ".join(skill_lines).strip(),
        elements=_parse_benchmark(benchmark_lines),
    )

    inputs = PlanInputs(
        trainer_name=heading.get("name of trainer", ""),
        institution=heading.get("institution", ""),
        course=heading.get("course", ""),
        level=heading.get("level", ""),
        num_trainees=heading.get("number of trainees", ""),
        class_code=heading.get("class", ""),
        date_of_preparation=heading.get("date of preparation", ""),
    )

    return unit, sessions, inputs
